In [1]:
import numpy as np

In [7]:
x=np.array(5)

In [8]:
x.ndim

0

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [5]:
np.array({1,2,3,4,5})#dont pass dictionaries

array({1, 2, 3, 4, 5}, dtype=object)

In [6]:
np.array({1:2,3:4})

array({1: 2, 3: 4}, dtype=object)

In [7]:
np.array("jdfhkek")

array('jdfhkek', dtype='<U7')

In [13]:
x=np.array(10)

In [14]:
x.ndim

0

In [15]:
x.shape

()

In [10]:
x=np.array([10])

In [11]:
x.ndim

1

In [12]:
x=np.array([[10]])

In [13]:
x.ndim

2

In [16]:
x=np.array([[[10]]])

In [17]:
x.ndim

3

In [18]:
type(x)

numpy.ndarray

In [15]:
np.array(5,ndmin=6)

array([[[[[[5]]]]]])

In [19]:
np.array([1,1.1,1+2j,"a"])

array(['1', '1.1', '(1+2j)', 'a'], dtype='<U64')

In [24]:
np.array([1,2,-3,-4],dtype=np.uint8)

array([  1,   2, 253, 252], dtype=uint8)

In [23]:
np.array([1,2,3,-27,-5],dtype=np.uint8)

array([  1,   2,   3, 229, 251], dtype=uint8)

In [25]:
x=np.array([1,2,3])

In [26]:
x.ndim

1

In [28]:
x.shape

(3,)

In [29]:
x

array([1, 2, 3])

In [9]:
x=np.array([[1,2,3]])

In [10]:
x.ndim

2

In [11]:
x

array([[1, 2, 3]])

In [36]:
x.shape

(1, 3)

In [12]:
x.size

3

In [37]:
x=np.array([[1,2,3],[1,2,3],[1,2,3]])

In [38]:
x.ndim

2

In [39]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [40]:
x.shape ##will always return in tuple format  (it is nothing but 3 row 3 columns)

(3, 3)

In [41]:
np.zeros((3,),dtype=int)

array([0, 0, 0])

In [43]:
np.zeros((10,),dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.zeros((10,20),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
np.zeros([5,10],dtype=int)##default will be float

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
import numpy as np
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [47]:
np.ones([4,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
np.full((2,5),11)

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [51]:
np.full((2,7),12,dtype=float)

array([[12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12.]])

In [53]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [54]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
import numpy as np

In [9]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [10]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [11]:
np.arange(100,110) ## 1 dim array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [14]:
np.arange(1,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [15]:
np.linspace(1,10,4)## 1 dimension

array([ 1.,  4.,  7., 10.])

In [16]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [18]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
np.linspace((1,2),(10,20),10)

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [8]:
np.linspace((1,2),(1,20),10)

array([[ 1.,  2.],
       [ 1.,  4.],
       [ 1.,  6.],
       [ 1.,  8.],
       [ 1., 10.],
       [ 1., 12.],
       [ 1., 14.],
       [ 1., 16.],
       [ 1., 18.],
       [ 1., 20.]])

In [19]:
np.random.random((3,4))

array([[0.07399767, 0.20869115, 0.2639169 , 0.42317982],
       [0.9428934 , 0.88240391, 0.98874692, 0.63869966],
       [0.41256176, 0.63186901, 0.48323397, 0.98936725]])

In [20]:
##1 dimensional array with 20 elements

In [21]:
np.random.random((20,))

array([0.04010803, 0.34348796, 0.05155203, 0.98028456, 0.07197697,
       0.52091181, 0.75901707, 0.91097945, 0.95891958, 0.01991259,
       0.47830302, 0.09419096, 0.31723537, 0.40266932, 0.1048622 ,
       0.95761085, 0.15684088, 0.21117162, 0.065815  , 0.52749966])

In [22]:
##creating a matrix with three rows and three columns

In [2]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
x[0:3,2:]

array([[3],
       [6],
       [9]])

In [18]:
x.ndim

2

In [25]:
x[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [19]:
x1=np.arange(1,5)

In [27]:
x1

array([1, 2, 3, 4])

In [20]:
x1[1:3]


array([2, 3])

In [29]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
x[0,0]

1

In [31]:
np.random.random((5,5))

array([[0.56349195, 0.37007331, 0.67584919, 0.42226675, 0.73816414],
       [0.07254757, 0.96283231, 0.68627267, 0.08459293, 0.2276414 ],
       [0.19923108, 0.4680875 , 0.98366486, 0.95639265, 0.06294423],
       [0.6814279 , 0.70788368, 0.00346695, 0.59883723, 0.16928984],
       [0.64362491, 0.9663037 , 0.10383357, 0.16522097, 0.94964783]])

In [22]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
y=x[1:,1:]

In [25]:
y

array([[5, 6],
       [8, 9]])

In [26]:
y[0,0]=100

In [27]:
y

array([[100,   6],
       [  8,   9]])

In [28]:
x

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [29]:
y

array([[100,   6],
       [  8,   9]])

In [30]:
y[1,1]=200

In [31]:
y

array([[100,   6],
       [  8, 200]])

In [32]:
x

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8, 200]])

In [33]:
x.ndim

2

In [37]:
y=x[[1,1,2,2],[1,2,2,1]]

In [38]:
y.ndim

1

In [36]:
y

array([100,   6,   8, 200])

In [47]:
x[[0,2],[0,1]]

array([1, 8])

In [48]:
x[[1,2],[0,2]]

array([  4, 200])

In [39]:
z=np.array([1,2,3],ndmin=3)

In [40]:
z

array([[[1, 2, 3]]])

In [50]:
x1=np.arange(1,10)
x2=np.arange(10,19)

In [51]:
x1.shape

(9,)

In [52]:
x2.shape

(9,)

In [53]:
x1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x2

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [55]:
x1+x2

array([11, 13, 15, 17, 19, 21, 23, 25, 27])

In [56]:
x1-x2

array([-9, -9, -9, -9, -9, -9, -9, -9, -9])

In [57]:
x1*x2

array([ 10,  22,  36,  52,  70,  90, 112, 136, 162])

In [58]:
x1/x2

array([0.1       , 0.18181818, 0.25      , 0.30769231, 0.35714286,
       0.4       , 0.4375    , 0.47058824, 0.5       ])

In [59]:
x1//x2

array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [60]:
x3=np.full((3,4),5)

In [61]:
x3

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [62]:
x4=np.full((3,4),7)

In [63]:
x4

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [64]:
x3+x4

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [45]:
np.random.randint(1,10)   # random.randint(start,stop)

2

In [43]:
import random
random.randrange(2,10,2)   # random.randrange(start,stop[,step])

8

In [41]:
#how to apply comparision opearater on array(<,>,=,<=,>=,!=)
##when applying comparision opearaters we get True or False

In [66]:
x1>x2

array([False, False, False, False, False, False, False, False, False])

In [67]:
x1<x2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [68]:
x1>=x2

array([False, False, False, False, False, False, False, False, False])

In [69]:
x1<=x2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [70]:
x1!=x2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [72]:
y=np.array([[1,2,3],[4,5,6],[8,9,7]])

In [73]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 7]])

In [74]:
x

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8, 200]])

In [75]:
x>y

array([[False, False, False],
       [False,  True, False],
       [False, False,  True]])

In [76]:
x<=y

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [77]:
##boolen based indexing

In [80]:
z=np.arange(1,21).reshape(4,5)

In [81]:
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [82]:
z[z%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])