In [1]:
# how to combine multiple array into a single array by using concatenation,column vise merging,row wise merging

In [49]:
import numpy as np
x1=np.arange(0,4).reshape(2,2)

In [50]:
x1

array([[0, 1],
       [2, 3]])

In [51]:
x2=np.arange(4,8).reshape(2,2)

In [52]:
x2

array([[4, 5],
       [6, 7]])

In [53]:
np.concatenate([x1,x2],axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [54]:
np.concatenate([x1,x2],axis=1)

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [55]:
np.hstack([x1,x2])

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [56]:
np.vstack([x1,x2])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [12]:
z=np.arange(20,30)

In [13]:
z

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
np.min(z)

20

In [16]:
np.argmin(z)   # get min index value

0

In [17]:
np.argmax(z)   #get max index value

9

In [18]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])

In [19]:
x

array([1, 2, 3, 4])

In [20]:
y

array([5, 6, 7, 8])

In [21]:
np.logical_and(x,y)

array([ True,  True,  True,  True])

In [22]:
np.logical_or(x,y)

array([ True,  True,  True,  True])

In [23]:
x=np.array([0,2,3,4])
y=np.array([5,6,7,8])

In [24]:
np.logical_and(x,y)

array([False,  True,  True,  True])

In [25]:
np.logical_or(x,y)

array([ True,  True,  True,  True])

In [26]:
# all=check only one array ,if all true ,return true or else return false
#  any=check only one array ,if any value is true,return true
  

In [27]:
z=np.arange(0,20,2).reshape(2,5)

In [28]:
z%2==0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [29]:
np.all(z%2==0)

True

In [31]:
np.all((z%2==0) & (z%3==0))

False

In [33]:
np.all((z%2==0) | (z%3==0))

True

In [34]:
np.any((z%2==0) & (z%3==0))

True

In [2]:
import numpy as np
c=np.random.randint(1,10,(20,))

In [3]:
c

array([1, 9, 4, 3, 9, 2, 7, 8, 6, 4, 4, 4, 1, 3, 6, 9, 1, 1, 7, 1])

In [4]:
w=np.sort(c)   # sort in increasing order

In [5]:
w

array([1, 1, 1, 1, 1, 2, 3, 3, 4, 4, 4, 4, 6, 6, 7, 7, 8, 9, 9, 9])

In [6]:
w[::-1]

array([9, 9, 9, 8, 7, 7, 6, 6, 4, 4, 4, 4, 3, 3, 2, 1, 1, 1, 1, 1])

In [7]:
w[0::]

array([1, 1, 1, 1, 1, 2, 3, 3, 4, 4, 4, 4, 6, 6, 7, 7, 8, 9, 9, 9])

In [40]:
c=np.random.randint(1,10,(10,15))

In [41]:
c

array([[9, 9, 3, 5, 1, 7, 2, 3, 6, 5, 6, 1, 5, 9, 2],
       [4, 9, 2, 7, 7, 7, 7, 5, 5, 6, 8, 1, 5, 3, 6],
       [2, 9, 1, 9, 7, 2, 8, 6, 7, 5, 4, 5, 9, 5, 7],
       [5, 8, 6, 8, 3, 1, 2, 6, 3, 3, 7, 5, 3, 2, 2],
       [3, 6, 9, 3, 3, 1, 5, 4, 7, 6, 3, 7, 5, 6, 9],
       [9, 7, 1, 2, 6, 4, 6, 3, 6, 2, 7, 7, 6, 1, 3],
       [6, 8, 4, 7, 9, 7, 6, 7, 2, 9, 9, 1, 2, 3, 5],
       [2, 5, 5, 9, 7, 7, 4, 6, 1, 1, 2, 1, 7, 8, 1],
       [5, 8, 7, 9, 7, 7, 7, 1, 1, 4, 4, 8, 6, 2, 7],
       [9, 4, 8, 1, 4, 6, 9, 3, 1, 1, 7, 5, 6, 1, 2]])

In [42]:
np.sort(c,axis=0)

array([[2, 4, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1],
       [2, 5, 1, 2, 3, 1, 2, 3, 1, 1, 3, 1, 3, 1, 2],
       [3, 6, 2, 3, 3, 2, 4, 3, 1, 2, 4, 1, 5, 2, 2],
       [4, 7, 3, 5, 4, 4, 5, 3, 2, 3, 4, 1, 5, 2, 2],
       [5, 8, 4, 7, 6, 6, 6, 4, 3, 4, 6, 5, 5, 3, 3],
       [5, 8, 5, 7, 7, 7, 6, 5, 5, 5, 7, 5, 6, 3, 5],
       [6, 8, 6, 8, 7, 7, 7, 6, 6, 5, 7, 5, 6, 5, 6],
       [9, 9, 7, 9, 7, 7, 7, 6, 6, 6, 7, 7, 6, 6, 7],
       [9, 9, 8, 9, 7, 7, 8, 6, 7, 6, 8, 7, 7, 8, 7],
       [9, 9, 9, 9, 9, 7, 9, 7, 7, 9, 9, 8, 9, 9, 9]])

In [43]:
np.sort(c,axis=1)

array([[1, 1, 2, 2, 3, 3, 5, 5, 5, 6, 6, 7, 9, 9, 9],
       [1, 2, 3, 4, 5, 5, 5, 6, 6, 7, 7, 7, 7, 8, 9],
       [1, 2, 2, 4, 5, 5, 5, 6, 7, 7, 7, 8, 9, 9, 9],
       [1, 2, 2, 2, 3, 3, 3, 3, 5, 5, 6, 6, 7, 8, 8],
       [1, 3, 3, 3, 3, 4, 5, 5, 6, 6, 6, 7, 7, 9, 9],
       [1, 1, 2, 2, 3, 3, 4, 6, 6, 6, 6, 7, 7, 7, 9],
       [1, 2, 2, 3, 4, 5, 6, 6, 7, 7, 7, 8, 9, 9, 9],
       [1, 1, 1, 1, 2, 2, 4, 5, 5, 6, 7, 7, 7, 8, 9],
       [1, 1, 2, 4, 4, 5, 6, 7, 7, 7, 7, 7, 8, 8, 9],
       [1, 1, 1, 1, 2, 3, 4, 4, 5, 6, 6, 7, 8, 9, 9]])

In [8]:
a=np.random.randint(1,10,(5,))

In [9]:
a

array([5, 8, 2, 8, 4])

In [10]:
np.sort(a)

array([2, 4, 5, 8, 8])

In [11]:
np.argsort(a)

array([2, 4, 0, 1, 3], dtype=int64)

In [12]:
import numpy as np
b=np.random.randint(1,10,(3,3))

In [13]:
b

array([[1, 9, 7],
       [8, 5, 8],
       [7, 5, 1]])

In [14]:
np.argsort(b[:,0])

array([0, 2, 1], dtype=int64)

In [15]:
b[np.argsort(b[:,0])]  

array([[1, 9, 7],
       [7, 5, 1],
       [8, 5, 8]])

In [16]:
b[np.argsort(b[:,2])]   

array([[7, 5, 1],
       [1, 9, 7],
       [8, 5, 8]])

In [17]:
b[np.argsort(b[1,:])]

array([[8, 5, 8],
       [1, 9, 7],
       [7, 5, 1]])

In [26]:
b

array([[5, 7, 2],
       [9, 3, 5],
       [7, 4, 5]])

In [27]:
b=b.astype(float)

In [28]:
b

array([[5., 7., 2.],
       [9., 3., 5.],
       [7., 4., 5.]])

In [29]:
b=b.astype(complex)

In [30]:
b

array([[5.+0.j, 7.+0.j, 2.+0.j],
       [9.+0.j, 3.+0.j, 5.+0.j],
       [7.+0.j, 4.+0.j, 5.+0.j]])

In [31]:
b=b.astype(int)

C:\Users\SSS\AppData\Local\Temp\ipykernel_3560\2615737369.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  b=b.astype(int)


In [32]:
b

array([[5, 7, 2],
       [9, 3, 5],
       [7, 4, 5]])

In [34]:
x=b[1:,1:]

In [35]:
x[0,0]=100

In [36]:
x

array([[100,   5],
       [  4,   5]])

In [37]:
b

array([[  5,   7,   2],
       [  9, 100,   5],
       [  7,   4,   5]])

In [85]:
x=np.arange(1,10)

In [86]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.save("C:\\Users\\SSS\\Desktop\\New folder\\sobana.npy",x)

In [91]:
b

array([[7, 1, 2],
       [8, 3, 8],
       [1, 3, 3]])

In [102]:
np.savez("C:\\Users\\SSS\\Desktop\\New folder (2)\\dev.npz",x,b)
w=np.load("C:\\Users\\SSS\\Desktop\\New folder (2)\\dev.npz")

In [103]:
b

array([[7, 1, 2],
       [8, 3, 8],
       [1, 3, 3]])

In [104]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
w

In [106]:
w.files

['arr_0', 'arr_1']

In [109]:
w['arr_0']

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
w['arr_1']

array([[7, 1, 2],
       [8, 3, 8],
       [1, 3, 3]])

In [93]:
# broadcasting 

In [107]:
np.arange(3)+5

array([5, 6, 7])

In [108]:
np.ones((3,3),dtype=int)+np.arange(3)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [99]:
np.arange(3).reshape(3,1)+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [16]:
u=np.arange(3)

In [17]:
u

array([0, 1, 2])

In [18]:
v=np.arange(3).reshape(3,1)

In [19]:
v

array([[0],
       [1],
       [2]])

In [20]:
u+v

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [18]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])