In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5])

In [3]:
np.sum(x)

15

In [4]:
x1=np.arange(1,10).reshape(3,3)

In [5]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.sum(x1)

45

In [7]:
np.sum(x1,axis=0)

array([12, 15, 18])

In [8]:
np.sum(x1,axis=1)

array([ 6, 15, 24])

In [9]:
np.prod(x1)

362880

In [10]:
np.prod(x1,axis=0)

array([ 28,  80, 162])

In [11]:
np.prod(x1,axis=1)

array([  6, 120, 504])

In [16]:
y=np.arange(1,10,dtype=float).reshape(3,3)

In [17]:
y

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [22]:
y[1,1]=np.nan

In [23]:
y

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [24]:
np.sum(y)

nan

In [25]:
np.nansum(y)

40.0

In [30]:
np.nansum(y,axis=0)

array([12., 10., 18.])

In [26]:
np.prod(y)

nan

In [27]:
np.nanprod(y)

72576.0

In [28]:
np.nanprod(y,axis=0)

array([ 28.,  16., 162.])

In [29]:
np.nanprod(y,axis=1)

array([  6.,  24., 504.])

In [31]:
z=np.array([1,2,3,4,5])
np.cumsum(z)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [32]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.cumsum(x1)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [34]:
np.cumsum(x1,axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [35]:
np.cumsum(x1,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [37]:
np.cumprod(x1,axis=0)

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]], dtype=int32)

In [39]:
np.cumprod(x1,axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)

In [38]:
np.cumprod(x1)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [40]:
y

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [41]:
np.nancumsum(y,axis=0)

array([[ 1.,  2.,  3.],
       [ 5.,  2.,  9.],
       [12., 10., 18.]])

In [42]:
np.nancumprod(y,axis=0)

array([[  1.,   2.,   3.],
       [  4.,   2.,  18.],
       [ 28.,  16., 162.]])

In [43]:
x

array([1, 2, 3, 4, 5])

In [44]:
np.min(x)

1

In [45]:
np.max(x)

5

In [46]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.min(x1,axis=0)

array([1, 2, 3])

In [48]:
np.max(x1,axis=1)

array([3, 6, 9])

In [49]:
y

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [50]:
np.nanmax(y,axis=0)

array([7., 8., 9.])

In [33]:
import numpy as np
a=np.arange(1,10,dtype=float).reshape(3,3)

In [34]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [35]:
a[0,0]=np.inf

In [36]:
a

array([[inf,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [37]:
np.sum(a)

inf

In [38]:
np.infmax(a,axis=1)

AttributeError: module 'numpy' has no attribute 'infmax'

In [39]:
a[np.isinf(a)]=0

In [40]:
a

array([[0., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [41]:
np.sum(a)

44.0

In [55]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [56]:
np.mean(a,axis=0)

array([4., 5., 6.])

In [57]:
b=np.array([1,2,3,4,5])

In [58]:
np.mean(b)

3.0

In [59]:
np.median(a,axis=1)

array([2., 5., 8.])

In [62]:
c=np.array([1,2,3,4,5,6])

In [63]:
np.median(c)

3.5

                    How to find out unique elements in n dimensional array

In [64]:
c=np.array([1,2,3,4,5,6])

In [65]:
np.unique(c)

array([1, 2, 3, 4, 5, 6])

In [66]:
c=np.array([1,2,3,1,1,4,2,3,3,5,6,4,5])

In [67]:
np.unique(c)

array([1, 2, 3, 4, 5, 6])

In [68]:
np.unique(c,return_counts=True)   # return_counts give count of each element

(array([1, 2, 3, 4, 5, 6]), array([3, 2, 3, 2, 2, 1], dtype=int64))

In [69]:
x1,y1=np.unique(c,return_counts=True)

In [70]:
x1

array([1, 2, 3, 4, 5, 6])

In [71]:
y1

array([3, 2, 3, 2, 2, 1], dtype=int64)

In [80]:
x3=np.arange(1,10).reshape(3,3)

In [81]:
x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
np.unique(x3,return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

                transpose

In [93]:
x=np.array([[1,2,3],[4,5,6]])

In [94]:
x.shape

(2, 3)

In [95]:
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [96]:
x=x.T

In [97]:
x

array([[1, 4],
       [2, 5],
       [3, 6]])

In [98]:
x.shape

(3, 2)

In [99]:
# flatten()----return copy of original array.If u modify the array ,value of original array is not affected.
# ravel()------return reference/view of original array.If u modify the array ,value of original array also changes.

In [59]:
x1=np.arange(1,10).reshape(3,3)

In [60]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
x1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
x1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
y=x1.ravel()

In [64]:
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
y[0]=0

In [67]:
y

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
x1

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
b=x1.flatten()

In [70]:
b

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
b[0]=100

In [72]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [73]:
x1

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
#   how to repeat the elements n no.of times

In [135]:
x=np.array([1,2,3,4,5])

In [136]:
x

array([1, 2, 3, 4, 5])

In [137]:
np.repeat(x)

TypeError: _repeat_dispatcher() missing 1 required positional argument: 'repeats'

In [119]:
np.repeat(x,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [120]:
np.repeat(x,5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5])

In [131]:
x=np.arange(1,10).reshape(3,3)

In [132]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
np.repeat(x,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [125]:
# how to repeat the array n no. of time

In [126]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
np.tile(x,2)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [128]:
np.tile(x,5)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [129]:
np.tile(x,(1,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [130]:
np.tile(x,(2,1))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
# try to create zero function on your own

In [1]:
def zero(rows,columns,matrix=[]):
    for x in range(0,rows):
        matrix.append([0 for y in range(0,rows)])
        return matrix

In [2]:
zero(2,3)

[[0, 0]]

In [85]:
def zero(rows,columns,matrix=[]):
    for x in range(0,rows):
        matrix.append(x)
        return matrix
    for y in range(0,coumns):
        matrix.append(y)
        return matrix
zero(2,3)    

[0]

In [43]:
x=np.arange(1,10).reshape(3,3)

In [44]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [56]:
def zeros(n,m=0):
    l=[]
    if m==0:
        for z in range(n):
            l.append(0)
    else:
        for y in range(n):
            l.append([])
            for z in range(m):
                l[y].append(0)
    
    return l             

In [58]:
zeros(5,2)

[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]

In [4]:
def ones(n,m=0):
    l=[]
    if m==0:
        for z in range(n):
            l.append(1)
    else:
        for y in range(n):
            l.append([])
            for z in range(m):
                l[y].append(1)
    
    return l 
ones(5,2)

[[1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]

In [53]:
l=[]
for y in range(3):
        l.append([])

In [54]:
l

[[], [], []]

In [1]:
def zeros(n,m=0):
    l=[]
    if m==0:
        for z in range(n):
            l.append(0)
    else:
        for y in range(n):
            l.append([])
            for z in range(m):
                l[y].append(0)
    
    return l             
zeros(5,0)

[0, 0, 0, 0, 0]

In [7]:
def diffnum(n,m=0):
    l=[]
    if m==0:
        for z in range(n):
            l.append(0)
    else:
        for y in range(n):
            l.append([])
            for z in range(m):
                l[y].extend(2)
    
    return l
diffnum(5,2)

TypeError: 'int' object is not iterable

In [1]:
import numpy as np

In [5]:
x=np.arange(1,16).reshape(5,3)

In [6]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [7]:
# get the index value
# where()

In [9]:
y=np.arange(1,10)

In [10]:
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
y>3

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [13]:
y[y>3]

array([4, 5, 6, 7, 8, 9])

In [14]:
np.where(y>3)

(array([3, 4, 5, 6, 7, 8], dtype=int64),)

In [15]:
z=np.arange(20,30)

In [16]:
z

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
z%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [18]:
np.where(z%2==0)    # this is index value

(array([0, 2, 4, 6, 8], dtype=int64),)

In [19]:
np.where((z%3==0) & (z%5==0))

(array([], dtype=int64),)

In [16]:
import numpy as np
x=np.arange(1,16).reshape(3,5)

In [17]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
x%2==0

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [19]:
np.where(x%2==0)  #1 st row values ,2 nd array column values

(array([0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([1, 3, 0, 2, 4, 1, 3], dtype=int64))

In [20]:
x=np.where(x%2==0)

In [21]:
x.take(np.where(x%2==0))

AttributeError: 'tuple' object has no attribute 'take'

In [9]:
import numpy as np
z=np.arange(20,30)

In [10]:
z

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
z.take(np.where(z%2==0))   #take function only work in 1d

array([[20, 22, 24, 26, 28]])

In [15]:
z

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
np.where(z>24,True,False)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [13]:
np.where(z>24,gr)

NameError: name 'greater' is not defined

In [37]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [38]:
x[x%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [39]:
np.where(x%2==0,True,False)

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [40]:
x[np.where(x%2==0,True,False)]

array([ 2,  4,  6,  8, 10, 12, 14])

In [41]:
np.where(x%2==0)

(array([0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([1, 3, 0, 2, 4, 1, 3], dtype=int64))